### ISSUE TITLE
Crash when Loading CraftMania texture pack

### ISSUE THREAD

**Issue by itsbumble** [LambdAurora/MCPatcherPatcher#15]
title
[crash-2021-02-26_13.18.59-client.txt](https://github.com/LambdAurora/MCPatcherPatcher/files/6051915/crash-2021-02-26_13.18.59-client.txt)

**Comment by LambdAurora** [comment]
The resource pack you're attempting to convert breaks Minecraft's identifier/path conventions.

No upper case character are allowed in those and one of its textures contains an upper case character.

You can attempt to convert the pack by using the standalone mode (so run the JAR instead of as a mod), it should open a GUI and let you select the pack ZIP and outputs a converted ZIP (which will only include the converted features).

I can't really fix this on my side for the mod mode as it would require me to do invasive change to Minecraft. I really hope one day OptiFine will stop breaking the game.

**Comment by itsbumble** [comment]
> The resource pack you're attempting to convert breaks Minecraft's identifier/path conventions.
> 
> No upper case character are allowed in those and one of its textures contains an upper case character.
> 
> You can attempt to convert the pack by using the standalone mode (so run the JAR instead of as a mod), it should open a GUI and let you select the pack ZIP and outputs a converted ZIP (which will only include the converted features).
> 
> I can't really fix this on my side for the mod mode as it would require me to do invasive change to Minecraft. I really hope one day OptiFine will stop breaking the game.

yeah okay makes sense, pretty bald on optifine's side
